name: Compilación Flet APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-level: '3.11'

      - name: Instala Flutter y el SDK de Android
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar Flet
        run: |
          pip install flet

      - name: Build APK
        run: |
          flet build apk --yes

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nota-calk-apk
          path: build/apk/*.apk