name: Build Flet APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flutter and Android SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flet
        run: |
          pip install flet

      - name: Build APK
        run: |
          flet build apk --no-public-ip

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nota-calk-apk
          path: build/apk/*.apk